languageCode: en-us
title: Nimisha Pokam
theme: digitalgarden
enableGitInfo: true

menu:
  main:
    - name: About Me
      url: /
      weight: 1
    
    - name: Education & Experience
      url: /career
      weight: 2
    
    - name: Projects
      url: /projects
      weight: 3

    - name: Tech Stack
      url: /stack
      weight: 4

  social:
    - name: GitHub
      url: https://github.com/NimishaPokam
      weight: 1
    - name: LinkedIn
      url: https://www.linkedin.com/in/nimisha-p-b1b9922a9/
      weight: 2
    - name: Email
      url: mailto:pnimisha@depaul.edu
      weight: 3
    - name: Instagram
      url: https://www.instagram.com/momwantsyouhomebydinner
      weight: 4
